- gradle/depend.gradle
Update versions with ATM ticketing
Update kotlin to 1.5.30
Update dagger (conflicts with kotlin 1.5.30)
> ATM Ticket version + update kotlin

- gradle/depend.gradle
> Fix bug in atm subscription purchase

- gradle/depend.gradle
https://github.com/urbi-mobility/android-telepass-pay-framework/issues/352
> Add brightness to ticket view

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TPU-5643
> TPU-5643 | Fixed bug in birthDate tag

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TPU-5697
> Driving license flow fix

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TPU-5754
> TPU-5754 | update version

- gradle/depend.gradle
[#368](https://github.com/urbi-mobility/android-telepass-pay-framework/issues/368)
[#367](https://github.com/urbi-mobility/android-telepass-pay-framework/issues/367)
[#364](https://github.com/urbi-mobility/android-telepass-pay-framework/issues/364)
> Update transpo version

- gradle/depend.gradle
Use "urbi $userId" as ATAC username
> Add custom ATAC username for Urbi

- gradle/depend.gradle
Fixed wrong ATM ticket description
> atm ticket desc

- gradle/depend.gradle
Update urbiscan to fix nfc scan crash
> removed unused NFC param reading

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TPU-6258
It seems that VOI kickscooters can be open with any code, and this can lead to open undesired vehicles.
Using "Find" method this will not happen cause it needs the correct code.
> TPU-6258 | Use Find to open vehicle

- gradle/depend.gradle
Era stato caricato erroneamente model anzichè core
> Version fix

- gradle/depend.gradle
Removed Instabug direct dependency
Fixed adding interceptor as networkInterceptor
> Fixed interceptor adding

- gradle/depend.gradle
Use chargingFormattedPrice everywhere to show recharging cost
> Add chargingFormattedPrice

- gradle/depend.gradle
> Fix UrbiPay

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TPU-6751
> TPU-6751 | Fix Hilt injection

- gradle/depend.gradle
https://github.com/urbi-mobility/urbi-react-native/issues/777
> #777 | Added email support

- gradle/depend.gradle
Aggiunta assistenza telefonica VOI
> TPU-6816 | Added VOI support phone version

- gradle/depend.gradle
> #514 | Added active reservation pin

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TPU-6758
> TPU-6758 | Update tpaylib version

- gradle/depend.gradle
https://github.com/urbi-mobility/android-telepass-pay-framework/issues/532
> #532 | Update EV Telepass FAQ

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TPU-6801
> Update T&C links

- gradle/depend.gradle
https://github.com/urbi-mobility/android-telepass-pay-framework/issues/530
> [taxi] mostrare indirizzo nel puntatore ad apertura sezione taxi

- gradle/depend.gradle
- scripts/build.gradle.kts
Aggiunto componente CardCode
Refactoring di alcune molecole
> Card code + clean

- gradle/depend.gradle
https://github.com/urbi-mobility/android-telepass-pay-framework/issues/538
> ITTAXIV2 new tpaylib version

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TPU-6979
https://telepass.atlassian.net/browse/TPU-6983
https://github.com/urbi-mobility/android-telepass-pay-framework/issues/519 (fix link pagamento penale)
> Fixes for taxi

- gradle/depend.gradle
Aggiunto provider FreeToX + aggiunta automatica di informazioni all'interno del body della mail di richiesta supporto
https://github.com/urbi-mobility/android-telepass-pay-framework/issues/521
https://telepass.atlassian.net/browse/TPU-6878
> TPU-6878, issue 521 | EV FreeToX + support body mail

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TPU-6996
> taxi bugfix

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TPU-7019
> 531 ev faq

- gradle/depend.gradle
https://github.com/urbi-mobility/android-telepass-pay-framework/issues/432
Aggiunto support email Helbiz (rimosso telefono Mimoto)
Aggiunte T&C Helbiz per Mimoto
> Update support and T&C for Mimoto

- gradle/depend.gradle
Added reservation prices for vehicles.
Mimoto has reservation costs, it's not free and it doesn't end
> Reservation prices

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TPU-7056
https://telepass.atlassian.net/browse/TPU-7052 rimosso Riprova
apiVersion -> 20220523
> Fixes for mobility

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TPU-7047
> TPU-7047 | Fixed molecule color

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TPU-7080
> TPU-7080 Update tpaylib version

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TPU-7105
> TPU 7105 [pickup point ] tap on user location

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TPU-7138
> tripo save to google pay button style

- gradle/depend.gradle
https://github.com/urbi-mobility/android-telepass-pay-framework/issues/556
> Bugfix [search] added missing translation 

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TCAR-135
> TCAR-135 | Update versions

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TPU-7201
> TPU-7201 | Update copy

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TPU-7253
> TPU-7253 | Update taxi copy

- gradle/depend.gradle
https://github.com/urbi-mobility/android-telepass-pay-framework/issues/639
> [tripo] google wallet button

- gradle/depend.gradle
https://github.com/wise-emotions/android-urbi-unica-framework/pull/55
> Hotfix tpaylib 2.8.2

- gradle/depend.gradle
Added providerSupportContact in EV
> #675 | Provider support contact

- gradle/depend.gradle
> Version Bump

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TPU-7349
https://github.com/urbi-mobility/android-telepass-pay-framework/issues/676
> #676, TPU-7439 | Taxi and EV label fixes

- gradle/depend.gradle
https://github.com/urbi-mobility/android-telepass-pay-framework/issues/689
> #689 | Added infos in scheduled ride view

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TPU-7373
> TPU-7373 | Fixed providerSupportContact use

- gradle/depend.gradle
https://telepass.atlassian.net/browse/RVAPT-214
https://telepass.atlassian.net/browse/RVAPT-286
> RVAPT-214, RVAPT-286 | Security vulnerability

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TLPURBI-30
> TLPURBI-30 | Comply SDK 31

- gradle/depend.gradle
Aggiunta dipendenza per la visualizzazione dei pdf
> Public transport map

- gradle/depend.gradle
> Version bumps

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TLPURBI-61
> ATAC fixes

- gradle/depend.gradle
> TCAR-904 | Update apegee url

- gradle/depend.gradle
https://github.com/urbi-mobility/android-urbi-framework/issues/760
https://github.com/urbi-mobility/android-urbi-framework/issues/766
> ATAC improvements

- gradle/depend.gradle
- scripts/build.gradle.kts
https://telepass.atlassian.net/browse/TLPURBI-17
https://telepass.atlassian.net/browse/TLPURBI-44
aggiunto bit in 26 città su Telepass
> BIT full integration

- scripts/build.gradle.kts
> Added Update scripts

- gradle/depend.gradle
> #566 | New version tpaylib

- gradle/depend.gradle
fix crash su atac che richiede SQL
> SQL dependency in Transpo

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TPU-7376
> fix for TPU 7376

- gradle/depend.gradle
https://github.com/urbi-mobility/android-urbi-framework/issues/809
> BIT scooter

- gradle/depend.gradle
> Move version app on App module

- gradle/depend.gradle
https://github.com/urbi-mobility/android-urbi-framework/issues/811
> #811 | ATM expiring alert

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TLPURBI-112
> TLPURBI-112| crash taxi

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TPAYX-3340
> TPAYX-3340 | FIX crash

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TLPURBI-129
https://github.com/urbi-mobility/android-urbi-framework/issues/840
Fixata una label nella view di ticket da attivare
Aggiunto loader in home e safe click listener all'acquisto per ATM, per contrastare gli acquisti multipli lamentati dagli utenti
> #840 | ATM fixes

- gradle/depend.gradle
Related JIRA ticket
https://telepass.atlassian.net/browse/TCAR-604
https://telepass.atlassian.net/browse/TCAR-1128
Description
Fuel:
improvement different experience between pre and post paid Fuel
show dialog when post paid fuel is completed
Motivation and context
Improve UX
Screenshots
N/A
> TCAR-640 | Fuel: improvement different experience between pre and post paid

- gradle/depend.gradle
https://github.com/urbi-mobility/android-urbi-framework/issues/594
https://github.com/urbi-mobility/android-urbi-framework/issues/855
https://github.com/urbi-mobility/android-urbi-framework/issues/856
> #855, #856, #594 | Fixes after feedbacks

- gradle/depend.gradle
https://github.com/urbi-mobility/android-urbi-framework/issues/840
> #840 | Fix error load tickets

- gradle/depend.gradle
https://github.com/wise-emotions/android-urbi-unica-framework/pull/74
> TCAR-922 | Fuel new stations: First and Giorgio Sprea

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TLPURBI-126
> Acea new EV provider

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TLPURBI-145
> TLPURBI-145 | Fixed device payload bug

- gradle/depend.gradle
Collegato a https://github.com/wise-emotions/android-urbi-unica-framework/pull/75
> Upload tpay network 2.8.0

- gradle/depend.gradle
https://github.com/urbi-mobility/android-urbi-framework/issues/924
> #924 | Taxi number

- gradle/depend.gradle
collegata a https://github.com/wise-emotions/android-urbi-unica-framework/pull/76
> TELPISO-64 | Change of the fuel price service endpoint on a single point of sale

- gradle/depend.gradle
https://github.com/urbi-mobility/android-urbi-framework/issues/993
https://github.com/urbi-mobility/android-urbi-framework/issues/998
https://github.com/urbi-mobility/android-urbi-framework/issues/1009 (un punto)
https://github.com/urbi-mobility/android-urbi-framework/issues/1005
> TAXI labels and ATAC update

- gradle/depend.gradle
https://github.com/urbi-mobility/android-urbi-framework/issues/951
Aggiunta logica generica di tracking ed eventi di screenview
> #951 | Added Analytics pt1

- gradle/depend.gradle
https://github.com/urbi-mobility/android-urbi-framework/issues/1057
> #1057 | QR Code scan check

- gradle/depend.gradle
https://github.com/urbi-mobility/android-urbi-framework/issues/1018
> #1018 | Codice sconto Trenitalia

- gradle/depend.gradle
Treni: Pulsante di conferma biglietto risulta non correttamente visibile #1115
> Done #1115

- gradle/depend.gradle
related to https://github.com/urbi-mobility/urbi-services-providers-files/issues/94
> #94 | Update tpaylib

- gradle/depend.gradle
Done [trip planner] - ListItemComparator Component #1091
> Update compose and kotlin

- gradle/depend.gradle
- gradle/libs.versions.toml
Addresses https://github.com/urbi-mobility/android-urbi-framework/issues/1242
> Version Catalogs

- gradle/libs.versions.toml
Addresses https://github.com/urbi-mobility/android-urbi-framework/issues/1274
```
2023-08-28 12:40:22.881 32259-32259 Adjust                  com.batsharing.android.debug         W  SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing!
2023-08-28 12:40:22.884 32259-32259 Adjust                  com.batsharing.android.debug         W  SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing!
2023-08-28 12:40:22.890 32259-32324 Adjust                  com.batsharing.android.debug         D  Read Attribution: tt:93gsqg3 tn:Organic net:Organic cam: adg: cre: cl: adid:12ab4ff25c40ceccafbc301a856eabc1 ct: ca:NaN cc: …
```
> feat: Integrate Adjust

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TELPISO-1248
> TELPISO-1248 | Fix orientation

- gradle/depend.gradle
> Restore UrbiNetwork methods

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TELPISO-1384
> Upload tpaylib 2.13.1

- gradle/depend.gradle
Upgrade `com.telepass.urbi.telepasslib` package version from `2.13.2` to `2.13.3`.
> Upgrade telepasslib Version

- gradle/libs.versions.toml
> Added webKit for Setting Proxy

- gradle/depend.gradle
> Upload tpaylib 2.13.7

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TLPURBI-273
Change icon
> TLPURBI-273 | Fix icon

- gradle/libs.versions.toml
Addresses https://github.com/urbi-mobility/android-urbi-framework/issues/1363
> #1363 Taxi Refactor

- gradle/depend.gradle
Disallineamento di un componente DS modificato
https://github.com/urbi-mobility/android-urbi-framework/issues/1464
> #1464 | Upload profile to align

- gradle/depend.gradle
https://github.com/wise-emotions/android-telepass-unica/pull/5813
Rollback TELPISO-3145
> TLPURBI-301, TELPISO-3145 | Update ATAC and move expired tickets, Rollback designsystem

- gradle/depend.gradle
- [Fix country order](https://telepass.atlassian.net/browse/TLPURBI-379)
- [Fix color add icon](https://telepass.atlassian.net/browse/TLPURBI-358)
- [Passaggio ponte extra](https://github.com/urbi-mobility/android-urbi-framework/issues/1696)
- [Visualizzazione giorno non corretta](https://github.com/urbi-mobility/android-urbi-framework/issues/1731)
- [Removed blackUrbi](https://telepass.atlassian.net/browse/TLPURBI-382)
> Upload new libs 6.4.12

- gradle/depend.gradle
> #1738 | Login crash

- gradle/depend.gradle
- scripts/build.gradle.kts
Come ho segnalato [qua](https://github.com/urbi-mobility/android-urbi-framework/pull/1940) ho eliminato il caricamente da telepass
> Uodate Scripts

- gradle/libs-urbi.versions.toml
Done #2045
Manca ancora la gestione della CI in quando devo creare lo script ma posso fare i test solo dopo il merge
> Added dependencyGuard

- gradle/depend.gradle
- https://telepass.atlassian.net/browse/TELPISO-5803
- https://telepass.atlassian.net/browse/TELPISO-5795
- https://telepass.atlassian.net/browse/TELPISO-5787
> fix: taxi scaffold

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TELPISO-5811
> fix: show cancellation note only for urbi

- gradle/depend.gradle
https://telepass.atlassian.net/browse/TELPISO-5947
> TELPISO-5947 | Update version

- gradle/libs-urbi.versions.toml
https://github.com/urbi-mobility/android-urbi-framework/issues/2363
> #2363 | Remove Adjust

- gradle/libs-urbi.versions.toml
https://github.com/urbi-mobility/android-urbi-framework/issues/2461#issuecomment-2684359050
> Added Facebook Core SDK

- gradle/depend.gradle
https://console.firebase.google.com/project/urbi-e256c/crashlytics/app/android:com.batsharing.android/issues/f4fd6e8c368b3fd2572a543a9f9721b3?utm_campaign=extensions&utm_medium=SLACK&utm_source=NEW_ANR_ISSUE&time=last-seven-days&versions=6.18%20(250781121)&sessionEventKey=67DBC8E80155000121A176F055018C17_2062248330784832754
> Fix crash serializable

- gradle/depend.gradle
- gradle/libs-urbi.versions.toml
https://github.com/urbi-mobility/android-urbi-framework/issues/2517
> ATAC update 2.2.2

- gradle/depend.gradle
- gradle/libs-urbi.versions.toml
https://telepass.atlassian.net/browse/TELPISO-7559
Needed for old SM in TPayX
> HOTFIX | TELPISO-7559 | Restore parsing Vehicle
